repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest -v -m critical
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit] 